### ISSUE TITLE
Coach's sans-serif font family needs to be HelveticaLTPro-Roman per designs

### ISSUE THREAD

**Issue by angellromero** [Tapestry-Inc/design-tokens#1]
Based on the new Coach designs, the san-serif font for Coach is expected to be `HelveticaLTPro-Roman`.  Can it be updated from within the design tokens?

Thanks in advanced

**Comment by ryanfitzer** [comment]
I'll get the correct details in this sprint. Not the easiest to track down :)

**Comment by ryanfitzer** [comment]
All the Coach fonts have been aligned to reference the correct font in the v1.0.0 release: https://assets.tapestry.com/ux/design-tokens/1.0.0/coach/index.html
