### ISSUE TITLE
Adding icons as design tokens 

### ISSUE THREAD

**Issue by angellromero** [Tapestry-Inc/design-tokens#2]
Per our last conversation @ryanfitzer, the plan was to add the svg icons as design tokens in the project. Is there a timeline as to when we can expect that in place so it can be leveraged in the Coach PWA implementation?

Thanks

**Comment by ryanfitzer** [comment]
These are now available:

```js
import myIcon from '@tapestry-inc/design-tokens/<brand>/icon/<group>/my-icon.svg';
```

https://assets.tapestry.com/ux/design-tokens/1.0.0/coach/index.html
