### ISSUE TITLE
Mixed protocol with the fonts url reference

### ISSUE THREAD

**Issue by Kassares** [Tapestry-Inc/design-tokens#22]
![image](https://user-images.githubusercontent.com/13994584/119640314-28a48180-be21-11eb-8e47-25e1426d349f.png)

**Comment by ryanfitzer** [comment]
Ah! Didn't realized that. Grabbed that directly from the font provider. Didn't notice the protocol issue. Thanks for letting me know. I'll get a fix released asap.
