### ISSUE TITLE
Bag icons have hardcoded values

### ISSUE THREAD

**Issue by andreilicsandru** [Tapestry-Inc/design-tokens#43]
Hello, 

The `bag.svg` and `bag-3digit.svg` icons for Coach in `navigation` have hardcoded values of `0` and `100`. Can you remove this placeholder values or create two more icons that are empty? We need to display realtime values inside the icon.

Thanks

**Comment by ryanfitzer** [comment]
@andreilicsandru I'll alert the UX team and get this updated.

**Comment by andreilicsandru** [comment]
Thanks @ryanfitzer.

**Comment by ryanfitzer** [comment]
@andreilicsandru Fixed in `v2.2.2`!

**Comment by andreilicsandru** [comment]
@ryanfitzer Looks good, thank you!
