### ISSUE TITLE
Coach design introduce a new gray hex value

### ISSUE THREAD

**Issue by angellromero** [Tapestry-Inc/design-tokens#5]
It appears that the Coach design introduces a new gray variant hex color for the strikethrough pricing dislay.  See screenshot.
In the short term, we are adding the variable into the project but figured it was worth calling out.

![Image 2021-05-06 at 1 45 08 PM](https://user-images.githubusercontent.com/810251/117350003-a81de100-ae71-11eb-86b3-4119594da2ad.jpg)

Thanks

**Comment by ryanfitzer** [comment]
Thanks for the heads-ups!

**Comment by ryanfitzer** [comment]
Ignore that close. Was supposed to release a v0.11.10, but released a v1.0.0 instead. Will resolve and updated the ticket.
